simple table with mock data
PromZona-Student/Hive-Geocaching pull request #14
Opened 2023-02-03 15:54 UTC by Mel-dev-hub

Created simple table with mock data from backend.

2023-02-06 12:02 UTC, kemm0 requested changes
I added some notes that should be fixed before merging

2023-02-06 12:02 UTC, kemm0 commented on frontend/src/components/GeocacheList/GeocacheList.tsx
> +    const [notes, setNotes] = useState([]);
Maybe the variable name would be more descriptive if it was geocaches instead of notes

2023-02-06 17:21 UTC, Mel-dev-hub reviewed
useEffect function is a bit different than suggested, changed api method a little. Let me know what you think.

2023-02-07 21:42 UTC, kemm0 commented
I think this is good for the first version 👍

2023-02-07 21:42 UTC, kemm0 approved these changes

2023-02-09 11:09 UTC, merged