3 add eslint rules for the project
PromZona-Student/Hive-Geocaching pull request #9
Opened 2023-01-26 11:18 UTC by kemm0

In this pull request I added eslint rules and created an example structure for the Homepage.

2023-01-26 11:20 UTC, kemm0 commented
This is just a test! don't merge

2023-01-26 11:25 UTC, visitharri requested changes
Do something differently

2023-01-26 11:27 UTC, visitharri approved these changes

2023-01-27 17:41 UTC, Mel-dev-hub approved these changes

2023-01-29 10:47 UTC, merged